require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

# Used for variables like `:passed_2`
Naming/VariableNumber:
  EnforcedStyle: snake_case
