language: ruby
rvm:
- ruby-head
- 2.3.0
- 2.2
- 2.1
matrix:
  allow_failures:
  - rvm: ruby-head
bundler_args: "--without development"
script:
- bundle exec rspec
env:
  global:
  - secure: xq/DNUIy1H7zfpWAMat7v/mjVKSWhl3LNxlhgMCNuDSsaPbUWWJNeJIMcjYDNK4JnnXe2S6pzYi2OZ5IzgEx9WotFZSF/v1syhFqfpkHn5IMiW+t5hyICBtbEli/lEB1yIz9Vmd9hDcWewRpIDxvZmpVOMFirxpbt0eXttG9G30jwx7Exp9mm9WaAbbjGzrEv4HwKMdZo1wtmteEbE9rlYAXqRHykySu3MmPl8JeBOwpLTNEF7KjrMPsgrwusgWDCTZmN026JmuuNG/wDjAWEx192z9FP1V7Cl5Qwpr3hkB6jKZl1+ZLULPXnP07QV5LbAWXQbEex77OS5PH6GATzAkchQU41id0W/XLD1z7lf1Gia8857sAEIAeNdPrExIbRA1T0VjpwVCHw2WWUodrB2J0yGos1+amAAmS6H5IF1cmVEGKgb54Gj6/y2NVe8L69Q0LmOAMV7mToLD/ULA0U6RevrKAGN3uorzZxwLSsXv1GxJdsI9QHOMdS+xY9pt2G9c5JEcGw3GaRkPXISg+vigwZHV3gIgNIe00GtYaL5u0ccdlFrW+MMAXXEIyWYUlrKls97FoC1qWnB1owdrBGpx2ECQvDi7znF2tABrN8/HpxDmnKCOpWhETGwedRfMw73SlQxYn9SXh6AAbNIBovnp9qt5t0Wpnzds8jaXvANA=
  - secure: EOMc3a6fb4nu7ioe/tSkwiG+6YAYAlnCg9pRoOQ1frhPnkkeFuDvaWkLj2OrZk61EIumfhfFxrJNfKzZb2bhqAJcKyUmdw74vxM/6PM3hrlsx6AU3Dw65sW6/c0qFF6N10l5PgighIx+qbMtQtJ3p6s0f96S/ESbrwmk0ffzs98oC0DBxXsBqIr3o9eiGQwOQdPvaK09b88ud1Q6xrD9qzTWzL1toKfNf+ZMe7/uEbGjdeA7D1/lImm73D49jWeV6+4tnxTAq0sOq2VlVFSd+09BstJUaAHN0QiLoXs9aupmwHtXaJKaJio+tiV8aAQqspdo4cKGWcL8q+mLMWTWgxNlJVWFM756xR2jhQVMEFlJMQYfUqMhHTPl29oRlVUlW5oDay0TEP7JuoHg43VecwICZz5+Rcq01ftB2ohW4x/oehBFCK4DrQ95/cjpJSXd53O2xq8f2My3v4co8atAyOhWHDQjhgsrziRu3c8A2Ybzn9BRocKdj8fRR73poBim5wP8qVH8Q9F1/ZBT+dsxsoCl3HsDQE2Gdn7qc6H/q9Bqzeo9hUzURv0XlStCAKlGiu2BYWO1Aag6nKM0rUZ2heoJRKy3cwOlptExg4BEJp/cKHHpjyEvvo/29nrr7W3sIsJAUXycCUxL98jSuTxogaI8k0pXbMEgiDStaBWT2YA=
