language: ruby
rvm:
- ruby-head
- 2.3.0
- 2.2
- 2.1
bundler_args: "--without development"
script:
- bundle exec rspec
env:
  global:
  - secure: xq/DNUIy1H7zfpWAMat7v/mjVKSWhl3LNxlhgMCNuDSsaPbUWWJNeJIMcjYDNK4JnnXe2S6pzYi2OZ5IzgEx9WotFZSF/v1syhFqfpkHn5IMiW+t5hyICBtbEli/lEB1yIz9Vmd9hDcWewRpIDxvZmpVOMFirxpbt0eXttG9G30jwx7Exp9mm9WaAbbjGzrEv4HwKMdZo1wtmteEbE9rlYAXqRHykySu3MmPl8JeBOwpLTNEF7KjrMPsgrwusgWDCTZmN026JmuuNG/wDjAWEx192z9FP1V7Cl5Qwpr3hkB6jKZl1+ZLULPXnP07QV5LbAWXQbEex77OS5PH6GATzAkchQU41id0W/XLD1z7lf1Gia8857sAEIAeNdPrExIbRA1T0VjpwVCHw2WWUodrB2J0yGos1+amAAmS6H5IF1cmVEGKgb54Gj6/y2NVe8L69Q0LmOAMV7mToLD/ULA0U6RevrKAGN3uorzZxwLSsXv1GxJdsI9QHOMdS+xY9pt2G9c5JEcGw3GaRkPXISg+vigwZHV3gIgNIe00GtYaL5u0ccdlFrW+MMAXXEIyWYUlrKls97FoC1qWnB1owdrBGpx2ECQvDi7znF2tABrN8/HpxDmnKCOpWhETGwedRfMw73SlQxYn9SXh6AAbNIBovnp9qt5t0Wpnzds8jaXvANA=
  - secure: Xh1yBDwLcssUoARDdyancictBuLWEsrFM3m8nPZqSHl3c65OfJJr/3cuOgmzQou2YoNYZ5CEXsgs5sCvreTERQVKPlck1dDovQC45vBYEtEsDn31v/dhOUob8n5S443WqtrqZlbbWKSA/0t/lcm2ATt4lImrlKj+wdd9qlj6wZ4P4E4feqlpmN4SA3IQYpq4uSXLrDlr482cf5Am8vmwnx8E0D17ol0tD7f5s/hw/CYc9AElYlGNRVVBFcaN3lDMWDKVbgWvPiARbpn/QzLwoudwWkQmSMpcOsISjBbiJHvcaZDhtzwsPtTU6DfxQA9g1YxjVdWpA7v2cTaLqGPC+yTkDooGcv9F+fjopYmZoqP1r5I95/tK9+R9d3uBBcX1PEZqdA0eNNhFPU/FdAJszwrBHQ0pzVKw6PXUwoDjo5mM4wODE3rQP+VaXtx+twxOcf3kMqoLe5FUk6xDO8JJBMwbOWt7jYoqy5WRpxvDv/ao3M/PLmlefn2qKX7Yw4OzPo2Xb1apKFKWWosgs3WiOj6J42L5mbPscO2zdeVJ5XJpwuLlETWN7n9HOgra5szPz6pQ39rpAXkskRsV7f+gbbviVEF3TWomhKasa8VVHFHGF1hdmB3XG+/VVRMIk2kU/jH2BU/vhcnmyGthl9thV4rtlfISJgtXq9K+Ts1+TT4=
